W7D3/Music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:new, :create,:destory, :show]
  resource :session, only:[:new, :create, :destroy]
  resources :bands do 
    resources :albums,only:[:new]
  end 

  resource :albums, only:[:create,:edit,:show,:update,:destroy]
end

W7D3/Music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  live       :boolean          not null
#  name       :string           not null
#  year       :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  band_id    :integer          not null
#
# Indexes
#
#  index_albums_on_band_id  (band_id)
#
class Album < ApplicationRecord
    validates :name, :year, presence: true
    validates :live, inclusion: {in: [true, false]}
    belongs_to :band,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: :Band
end

W7D3/Music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence: true
    has_many :albums,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: :Album
end

W7D3/Music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email          (email) UNIQUE
#  index_users_on_session_token  (session_token) UNIQUE
#
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length:{minimum: 6, allow_nil: true}
    after_initialize :ensure_session_token

    def self.generate_session_token
        SecureRandom.urlsafe_base64
    end 

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save
        self.session_token
    end 
    attr_reader :password
    
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end
    
    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end 

    def self.find_by_credentials(email,password)
        user = User.find_by(email: email)
        return nil if user.nil?
        user.is_password?(password) ? user : nil 
    end 
    private
    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end 
end

W7D3/Music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
   
    def show
        @albums = Album.find_by(id: params[:id])
        render :show
    end 

    def create
        @albums = Album.new(album_params)
        if @albums.save
            redirect_to album_url
        else  
            flash.now[:errors] = @albums.errors.full_messages
            render :new
        end 
    end 

    def new
        @band = Band.find(params[:band_id])
        @albums = Album.new(band_id: params[:band_id])
        render :new
    end 

    def edit
        @albums = Albums.find_by(id: params[:id])
        render :edit
    end 

    def update
        @albums = Albums.find_by(id: params[:id])
        if @albums.update(album_params)
            redirect_to album_url
        else 
            flash.now[:errors] = @albums.errors.full_messages
            render :edit
        end 
    end 

    def destory
        @albums = Albums.find_by(id: params[:id])
        @albums.destory
        redirect_to band_url(@albums.band_id)
    end 


    private

    def albums_params
        params.require(:album).require(:name,:band_id,:year,:live)
    end 
end

W7D3/Music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :logged_in?,:current_user

    def log_in_user!(user)
        session[:session_token]= user.reset_session_token!
    end 

    def logged_in?
        !!current_user
    end 

    def current_user
       @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def log_out
        if logged_in?
            current_user.reset_session_token!
        end
        session[:session_token] = nil 
        @current_user = nil 
    end 

    def require_login
        redirect_to new_session_url unless logged_in?
    end
    
    
end

W7D3/Music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
   
    def index 
        @bands = Band.all
        render :index 
    end 

    def show
        @band = Band.find_by(id: params[:id])
        render :show
    end 

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url
        else  
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end 
    end 

    def new
        @band = Band.new
        render :new
    end 

    def edit
        @band = Band.find_by(id: params[:id])
        render :edit
    end 

    def update
        @band = Band.find_by(id: params[:id])
        if @band.update(band_params)
            redirect_to band_url(@band)
        else 
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end 
    end 

    def destory
        @band = Band.find_by(id: params[:id])
        @band.destory
        redirect_to bands_url
    end 


    private

    def band_params
        params.require(:band).permit(:name)
    end 
end

W7D3/Music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user.nil?
            flash.now[:error] = ["Incorrect password/ email"]
            render :new 
        else 
            log_in_user!(user)
            redirect_to user_url(user)
        end
    end 

    def new
       render :new
    end 

    def destroy
         log_out
         redirect_to new_session_url 
    end 
end

W7D3/Music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end 

    def show
        @user = User.find_by(id: params[:id])
        render :show 
    end 
    def create
        @user = User.new(user_params)
        if @user.save
            log_in_user!(@user)
            redirect_to user_url(@user)
        else 
            flash.now[:errors] = @user.errors.full_messages
            render :new 
        end  
    end 


    private
    def user_params
        params.require(:user).permit(:email,:password)
    end 
end

W7D3/Music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W7D3/Music_app/app/helpers/application_helper.rb
module ApplicationHelper
   def auth_token
    "<input type='hidden' name= 'authenticity_token' value= '#{form_authenticity_token}'/>".html_safe
   end 
end

W7D3/Music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W7D3/Music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D3/Music_app/app/helpers/users_helper.rb
module UsersHelper
end

W7D3/Music_app/app/views/albums/_form.html.erb
<% if type == :new%>
    <%action_url = albums_url%>
    <%button_text = "Create Album"%>
<%elsif type = :edit%>
    <%action_url = album_url(album)%>
    <%button_text ="Update Album"%>
<%end%>

<form  action = <%=action_url%> method = "Post">
    <%=auth_token%>
    <%if type== :edit%>
        <input type = "hidden" name="_method" value = "patch">
    <%end%>

    <label for = name>Name
    <input type= "text" name = album[name] id="album.name" value=<%=album.name%>>
    </label>

    <label for="album_band">Band </label>
    <select name="album[band_id]" id ="album_band">
        <%Band.each do |band|%>
            <option value="<%=band.id%>"<%="selected" if album.band_id == band.id%>>
            </option>
        <%end%>
    </select>

    <label for= "album_live">Live</label>
        <input type = "raido" name=album[live] id="album.live">
        <%="checked" if album.live%>
    <label for="album_live1">Studio</label>  
        <input type = "raido" name=album[live] id="album.live">
        <%="checked" if !album.live%>

    <label for ="album_year"> Year</label>
    <input id="album-year" type="number" name=album[year] value="<%album.year%>">
    
    <input type="submit" value=<%=button_text%>>
</form>

W7D3/Music_app/app/views/albums/edit.html.erb
<h2>Update <%=@album.name%>></h2>
<%= render 'form', album: @album, type: :edit %>

W7D3/Music_app/app/views/albums/new.html.erb
<h2>New Album</h2>
<%= render 'form', album: @album, type: :new %>

W7D3/Music_app/app/views/albums/show.html.erb
<a href=<%= edit_albums_url(@album) %>>Edit album</a>
<form action=<%= albums_url(@album) %> method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete album">
<ul>
    <li>
        <%=@album.name%>
    </li>

    <li>
        <%=@album.band%>
    </li>

    <li>
        <%=@album.live%>
    </li>

    <li>
        <%=@album.year%>
    </li>
</ul>
</form>

W7D3/Music_app/app/views/bands/_form.html.erb
<% if type == :new%>
    <%action_url = bands_url%>
    <%button_text = "Create Band"%>
<%elsif type = :edit%>
    <%action_url = band_url(band)%>
    <%button_text ="Update Band"%>
<%end%>

<form  action = <%=action_url%> method = "Post">
    <%=auth_token%>
    <%if type== :edit%>
        <input type = "hidden" name="_method" value = "patch">
    <%end%>

    <label for = name>Name:
    <input type= "text" name = band[name] id="band.name" value=<%=band.name%>>
    </label>

    <input type="submit" value=<%=button_text%>>
    
</form>

W7D3/Music_app/app/views/bands/edit.html.erb
<h2>Update <%=@band.name%>></h2>
<%= render 'form', band: @band, type: :edit %>

W7D3/Music_app/app/views/bands/index.html.erb
<h1>All Bands</h1>
<a href="<%= new_band_url %>">New Band</a>
<ul>
    <%@bands.each do |band| %>
    <li><%=band.name%></li>
    <%end%>
<ul>

W7D3/Music_app/app/views/bands/new.html.erb
<h2>New Band</h2>
<%= render 'form', band: @band, type: :new %>

W7D3/Music_app/app/views/bands/show.html.erb
<h1><%@band.name%><h1>
<a href=<%= edit_band_url(@band) %>> Edit this band</a>
<ul>
    <%@band.albums.each do |album|%>
    <li><a href="<%=album_url(album)%>"> <%=album.name%></li>
    <%end%>
</ul>

W7D3/Music_app/app/views/layouts/application.html.erb
<html>
  <head>
    <title>Music App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <h2>Welcome, <%= current_user.email %></h2>
    <form action="<%= session_url %>" method="POST">
      <%=auth_token%>
      <input name="_method" type="hidden" value="DELETE">
      <input type="submit" value="Logout">
    </form>
    <% else %>
    <a href="<%= new_session_url %>">Login</a>
    <%end%>

    <% if flash[:errors] %>
    <% flash[:errors].each do |error|%>
      <%= error %>
    <% end %>
    <%end%>
    
    <%= yield %>
  </body>



</html>

W7D3/Music_app/app/views/users/new.html.erb
<!DOCTYPE html>

<h1>New user</h1>
<form action="<%=users_url%>" method="POST">
<%= auth_token %>
<label for="email">Email:
    <input type="text" name="user[email]" id="email"value=<%= @user.email%>>
</label>
<br><br>
<label for="password">Password:
    <input type="text" name="user[password]" id="password" value=<%=@user.password%>>
</label>

<br><br>

<input type="submit" value="Create User">

</form>

W7D3/Music_app/app/views/users/show.html.erb
<h1 >Profile</h1>
<div>
  Email: <%= current_user.email %>
</div>